# Generated by Django 5.0.14 on 2026-10-07 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título del Libro')),
                ('autor', models.CharField(max_length=150, verbose_name='Autor')),
                ('precio', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='El precio debe ser mayor a cero')])),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='El stock no puede ser negativo')])),
            ],
        ),
    ]
